import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../layouts/Navbar";
import Table from "../components/Table/Table";
import { useUiStore } from "../store/UI.store";
import AddStockModal from "../components/Modals/AddStockModal";
import ModalTitle from "../components/Modals/elements/ModalTitle";
import AddStockForm from "../components/Forms/AddStockForm";
import { useStocksStore } from "../store/stocks.store";
import { useRouter } from "next/router";

export default function Home() {
  const navigate = useRouter();

  navigate.push("/csv");

  const showAddForm = useUiStore((state: any) => state.showAddForm);
  const singleStock = useStocksStore((state: any) => state.singleStock);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {showAddForm && (
          <AddStockModal>
            <ModalTitle title="Agregar simbolo" />
            <AddStockForm stock={singleStock} />
          </AddStockModal>
        )}
        <Table />
      </main>
    </div>
  );
}
